### ISSUE TITLE
Adding Visitor Counter

### ISSUE THREAD

**Issue by cpalte** [cpalte/CloudResumeChallenge#2]
# Epic Title

Feature: Adding Visitor Counter

## Epic Description

This Feature will add a counter to the page, counting how many people visited the page. The counter will be saved in DynamoDB. Communication to DynamoDB via API Gateway and lambda function. The intrastructure will include a test.

## List of Tasks (Complete in order)

1. [ ] [Task 1: add Javascript](https://github.com/cpalte/CloudResumeChallenge/issues/1)
2. [ ] [Task 2: add DynamoDB](https://github.com/cpalte/CloudResumeChallenge/issues/2)
3. [ ] [Task 3: add API Gateway and lambda function](https://github.com/cpalte/CloudResumeChallenge/issues/2)
4. [ ] [Task 4: add testing](https://github.com/cpalte/CloudResumeChallenge/issues/2)
